void count_vowels_and_consonants(char *, int *, int *);
int count_word_in_str_way_1(char *, char *);
char * get_last_word(char *);
char * get_sub_string(char *, int, int);
char * find_common_route(char * hacklist, char *codelist, int *cost);
int isValidEmail(char *email);
int isSTRMatched(char *str1, char *str2);
char *performOperation(char *str1, char *str2, char *operation);
int count_word_int_str_way_2_recursion(char *str, char *word);
int findlen(char *s);